---
title: "RepData_PeerAssessment"
output: html_document
date: "`r Sys.Date()`"
---

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE}
library(dplyr)
library(xtable)
data <- read.table(file = "data/activity.csv", sep = ",", header = TRUE)
steps_df_day <- data %>% 
  group_by(date) %>% 
  summarise(steps_sum = sum(steps, na.rm = T), steps_mean = mean(steps, na.rm=T), steps_med = median(steps, na.rm=T))

mean_tot_steps_day <- round(mean(steps_df_day$steps_sum, na.rm = T), digits = 0) 
med_tot_steps_day <- median(steps_df_day$steps_sum, na.rm =T)
```

The mean of the total steps per day `r mean_tot_steps_day` is and the median is `r med_tot_steps_day`.

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE}

hist(steps_df_day$steps_sum)
print(steps_df_day %>% select(date, steps_sum), n= nrow(steps_df_day))
```

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE}

steps_df_int <- data %>% 
  group_by(interval) %>% 
  summarise(steps_sum = sum(steps, na.rm = T), steps_mean = mean(steps, na.rm=T), steps_med = median(steps, na.rm=T))
plot(steps_df_int$steps_mean, x= steps_df_int$interval)
test <- steps_df_int[steps_df_int$steps_mean == max(steps_df_int$steps_mean),1]
```

The interval with the most steps on average is `r test`.

```{r echo=F, message=FALSE, warning=FALSE, paged.print=FALSE}
data2 <- data
data2$steps <- apply(data, 1, function(x) steps_df_int$steps_mean[steps_df_int$interval == gsub(x['interval'], pattern = ' ', replacement = '')])
steps_df2_day <- data2 %>% 
  group_by(date) %>% 
  summarise(steps_sum = sum(steps, na.rm = T), steps_mean = mean(steps, na.rm=T), steps_med = median(steps, na.rm=T))

mean_tot_steps_day <- round(mean(steps_df_day$steps_sum, na.rm = T), digits = 0) 
med_tot_steps_day <- median(steps_df_day$steps_sum, na.rm =T)
```
